services:
  - type: web
    name: design-system-cria
    env: node
    plan: free
    buildCommand: npm install && npm run build:web
    startCommand: npm run start:web
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./dist
